const I18N={
  he:{'nav.home':'בית','nav.people':'אנשים','nav.stay':'לינה','nav.finance':'כספים','nav.more':'עוד'},
  en:{'nav.home':'Home','nav.people':'People','nav.stay':'Stay','nav.finance':'Finance','nav.more':'More'}
};
const seed={
  settings:{lang:'he',eventName:'ראש השנה באומן',start:'2027-09-30',end:'2027-10-05',currency:'USD',location:'Uman, Ukraine'},
  people:[
    {id:1,name:'יונתן לוי',phone:'+972 50-555-0101',passport:'27/08/2028',flight:'LY 611',room:'Apt 12 · Bed 2',paid:1850,balance:0,status:'confirmed'},
    {id:2,name:'יוסף כהן',phone:'+972 52-444-1122',passport:'14/11/2026',flight:'W6 1559',room:'Apt 8 · Bed 1',paid:1200,balance:650,status:'confirmed'},
    {id:3,name:'משה פרידמן',phone:'+972 54-221-3377',passport:'05/09/2027',flight:'LY 611',room:'Apt 12 · Bed 3',paid:900,balance:950,status:'pending'},
    {id:4,name:'דוד רוזן',phone:'+972 50-812-7744',passport:'02/07/2029',flight:'W6 1559',room:'לא שובץ',paid:1850,balance:0,status:'confirmed'}
  ],
  apartments:[
    {id:1,name:'Apartment 12',address:'Pushkina 18',capacity:8,occupied:7,manager:'יוסף',status:'active'},
    {id:2,name:'Apartment 8',address:'Sadova 6',capacity:6,occupied:5,manager:'יונתן',status:'active'},
    {id:3,name:'Apartment 3',address:'Nebesnoi Sotni 14',capacity:10,occupied:9,manager:'יוסף',status:'active'}
  ],
  flights:[
    {id:1,number:'LY 611',from:'TLV',to:'WAW',depart:'2027-09-30 06:15',arrive:'2027-09-30 09:10',passengers:22,status:'confirmed'},
    {id:2,number:'W6 1559',from:'TLV',to:'KRK',depart:'2027-09-30 11:30',arrive:'2027-09-30 14:10',passengers:18,status:'confirmed'},
    {id:3,number:'LO 152',from:'WAW',to:'TLV',depart:'2027-10-05 18:10',arrive:'2027-10-05 22:55',passengers:20,status:'planned'}
  ],
  transport:[
    {id:1,type:'Bus',name:'Bus 01',driver:'Oleksandr',phone:'+380 67 555 2201',capacity:50,status:'available'},
    {id:2,type:'Van',name:'Van 03',driver:'Mykola',phone:'+380 93 114 0088',capacity:8,status:'busy'},
    {id:3,type:'Car',name:'Car 07',driver:'Andrii',phone:'+380 63 441 9010',capacity:4,status:'available'}
  ],
  tasks:[
    {id:1,title:'אישור רשימת חדרים',owner:'יוסף',due:'2027-09-20',priority:'urgent',status:'pending'},
    {id:2,title:'סגירת הסעה מוורשה',owner:'יונתן',due:'2027-09-23',priority:'high',status:'pending'},
    {id:3,title:'שליחת פרטי טיסה לקבוצה',owner:'יונתן',due:'2027-09-25',priority:'normal',status:'done'}
  ],
  payments:[
    {id:1,person:'יונתן לוי',due:1850,paid:1850,status:'paid'},
    {id:2,person:'יוסף כהן',due:1850,paid:1200,status:'partial'},
    {id:3,person:'משה פרידמן',due:1850,paid:900,status:'partial'},
    {id:4,person:'דוד רוזן',due:1850,paid:1850,status:'paid'}
  ],
  expenses:[
    {id:1,category:'לינה',description:'מקדמה דירות',amount:4200,date:'2027-08-01'},
    {id:2,category:'תחבורה',description:'מקדמה אוטובוס',amount:1600,date:'2027-08-12'},
    {id:3,category:'כללי',description:'סים מקומי וניהול',amount:280,date:'2027-09-01'}
  ],
  issues:[
    {id:1,apartment:'Apartment 12',title:'אין מים חמים',severity:'high',status:'open',owner:'יוסף'},
    {id:2,apartment:'Apartment 8',title:'חסר מפתח נוסף',severity:'medium',status:'open',owner:'יונתן'},
    {id:3,apartment:'Apartment 3',title:'בדיקת מיטה מתקפלת',severity:'low',status:'resolved',owner:'יוסף'}
  ],
  schedule:[
    {id:1,date:'2027-09-30',time:'06:15',title:'יציאת טיסת LY 611',type:'flight'},
    {id:2,date:'2027-09-30',time:'11:30',title:'יציאת טיסת W6 1559',type:'flight'},
    {id:3,date:'2027-10-01',time:'08:30',title:'תדריך מנהלים',type:'meeting'},
    {id:4,date:'2027-10-02',time:'10:00',title:'מעבר בדירות ובדיקת תקלות',type:'stay'}
  ]
};
let state=loadState();
let route='dashboard';

function loadState(){try{const v=localStorage.getItem('uman_event_manager_v1');return v?JSON.parse(v):structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem('uman_event_manager_v1',JSON.stringify(state))}
function q(s){return document.querySelector(s)}
function qa(s){return [...document.querySelectorAll(s)]}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(n){return new Intl.NumberFormat(state.settings.lang==='he'?'he-IL':'en-US',{style:'currency',currency:state.settings.currency,maximumFractionDigits:0}).format(Number(n||0))}
function t(k){return I18N[state.settings.lang]?.[k]||I18N.en[k]||k}
function toast(msg){const el=q('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>el.classList.remove('show'),2200)}
function daysUntil(){const now=new Date();const d=new Date(state.settings.start+'T00:00:00');return Math.max(0,Math.ceil((d-now)/86400000))}
function countdown(){const d=new Date(state.settings.start+'T00:00:00');let ms=Math.max(0,d-new Date());const days=Math.floor(ms/86400000);ms%=86400000;const hours=Math.floor(ms/3600000);ms%=3600000;const mins=Math.floor(ms/60000);const sec=Math.floor((ms%60000)/1000);return {days,hours,mins,sec}}
function chip(text,type=''){return `<span class="chip ${type}">${esc(text)}</span>`}
function pageHead(title,sub='',action=''){return `<div class="page-head"><div><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div>${action}</div>`}
function statusHe(s){return ({confirmed:'מאושר',pending:'ממתין',active:'פעיל',planned:'מתוכנן',paid:'שולם',partial:'חלקי',open:'פתוח',resolved:'טופל',available:'זמין',busy:'עסוק',done:'בוצע'}[s]||s)}
function statusType(s){return ['confirmed','paid','resolved','available','done','active'].includes(s)?'green':['pending','partial','planned','busy'].includes(s)?'gold':['open'].includes(s)?'red':''}

const routes={
 dashboard:renderDashboard,people:renderPeople,stay:renderStay,finance:renderFinance,more:renderMore,
 flights:renderFlights,transport:renderTransport,tasks:renderTasks,issues:renderIssues,schedule:renderSchedule,settings:renderSettings
};
function navigate(r){route=r;if(!routes[r])r='dashboard';qa('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===r));routes[r]();window.scrollTo({top:0,behavior:'smooth'});location.hash=r}

function renderDashboard(){
 const c=countdown();const people=state.people.length;const beds=state.apartments.reduce((a,x)=>a+x.capacity,0);const occ=state.apartments.reduce((a,x)=>a+x.occupied,0);const pending=state.tasks.filter(x=>x.status!=='done').length;const balance=state.payments.reduce((a,x)=>a+Math.max(0,x.due-x.paid),0);
 q('#view').innerHTML=`<section class="page">
  <div class="hero"><div class="hero-copy"><h2>Rosh Hashanah in Uman</h2><div class="hero-sub">Together to a Brighter Year</div><div class="hero-meta"><span>📅 ${esc(state.settings.start)} – ${esc(state.settings.end)}</span><span>📍 ${esc(state.settings.location)}</span></div></div>
  <div class="countdown"><div class="count-units"><div class="count-unit"><strong>${c.days}</strong><small>DAYS</small></div><div class="count-unit"><strong>${String(c.hours).padStart(2,'0')}</strong><small>HOURS</small></div><div class="count-unit"><strong>${String(c.mins).padStart(2,'0')}</strong><small>MINUTES</small></div><div class="count-unit"><strong>${String(c.sec).padStart(2,'0')}</strong><small>SECONDS</small></div></div><button class="trip-pill">✈ Until the Trip</button></div></div>
  <div class="stat-grid">
    <div class="stat-card"><div class="stat-icon">👥</div><strong>${people}</strong><div class="label">מטיילים</div><small>${state.people.filter(p=>p.status==='pending').length} ממתינים לאישור</small></div>
    <div class="stat-card"><div class="stat-icon">⌂</div><strong>${occ} / ${beds}</strong><div class="label">תפוסת לינה</div><div class="progress"><span style="width:${beds?Math.round(occ/beds*100):0}%"></span></div></div>
    <div class="stat-card"><div class="stat-icon">☑</div><strong>${pending}</strong><div class="label">משימות פתוחות</div><small class="danger">${state.tasks.filter(x=>x.priority==='urgent'&&x.status!=='done').length} דחופות</small></div>
    <div class="stat-card"><div class="stat-icon">▣</div><strong>${money(balance)}</strong><div class="label">יתרות לתשלום</div><small>${state.payments.filter(x=>x.due>x.paid).length} אנשים</small></div>
  </div>
  <div class="quick-grid">
    ${quick('people','👥','משתתפים')}${quick('stay','⌂','חדרים ולינה')}${quick('flights','✈','טיסות')}${quick('finance','▣','תשלומים','gold')}
  </div>
  ${alertsCard()}
  ${scheduleCard()}
 </section>`;
}
function quick(r,icon,label,cls=''){return `<button class="quick-card ${cls}" onclick="navigate('${r}')"><span class="quick-icon">${icon}</span><strong>${label}<span>›</span></strong></button>`}
function alertsCard(){const alerts=[];state.people.filter(p=>new Date(p.passport.split('/').reverse().join('-')) < new Date(state.settings.end)).forEach(p=>alerts.push({icon:'🛂',type:'red',title:`דרכון דורש בדיקה: ${p.name}`,sub:p.passport,route:'people'}));state.payments.filter(x=>x.due>x.paid).slice(0,1).forEach(()=>alerts.push({icon:'▣',type:'gold',title:`${state.payments.filter(x=>x.due>x.paid).length} משתתפים עם יתרה`,sub:`סה״כ ${money(state.payments.reduce((a,x)=>a+Math.max(0,x.due-x.paid),0))}`,route:'finance'}));state.issues.filter(x=>x.status==='open').slice(0,1).forEach(i=>alerts.push({icon:'⌂',type:'gold',title:`תקלה ב-${i.apartment}`,sub:i.title,route:'issues'}));return `<div class="card"><div class="section-head"><div class="section-title">🔔 התראות</div><button class="section-link" onclick="navigate('more')">הצג הכל ›</button></div><div class="list">${alerts.length?alerts.map(a=>`<div class="row alert-${a.type}"><div class="row-icon ${a.type}">${a.icon}</div><div class="row-main"><strong>${esc(a.title)}</strong><span>${esc(a.sub)}</span></div><button class="row-action" onclick="navigate('${a.route}')">צפה ›</button></div>`).join(''):'<div class="empty">אין התראות פעילות</div>'}</div></div>`}
function scheduleCard(){const items=[...state.schedule].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,3);return `<div class="card"><div class="section-head"><div class="section-title">🗓 לוח זמנים קרוב</div><button class="section-link" onclick="navigate('schedule')">הצג הכל ›</button></div><div class="list">${items.map(i=>{const d=new Date(i.date+'T00:00:00');return `<div class="row"><div class="date-badge"><small>${d.toLocaleString('en',{month:'short'}).toUpperCase()}</small><strong>${d.getDate()}</strong></div><div class="row-main"><strong>${esc(i.title)}</strong><span>${esc(i.time)} · ${esc(i.type)}</span></div>${chip(i.type,'')}</div>`}).join('')}</div></div>`}

function renderPeople(){q('#view').innerHTML=`<section class="page">${pageHead('משתתפים','ניהול פרטי המשתתפים, נסיעה, לינה ותשלום',`<button class="btn primary" onclick="openPersonForm()">＋ משתתף</button>`)}<div class="toolbar"><div class="search">🔎<input id="peopleSearch" placeholder="חיפוש לפי שם, טלפון או טיסה" oninput="filterPeople()"></div><button class="btn secondary" onclick="exportCsv('people')">ייצוא CSV</button></div><div id="peopleTable">${peopleTable(state.people)}</div></section>`}
function peopleTable(rows){return `<div class="table-wrap"><table><thead><tr><th>שם</th><th>טלפון</th><th>דרכון</th><th>טיסה</th><th>לינה</th><th>יתרה</th><th>סטטוס</th><th></th></tr></thead><tbody>${rows.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.phone)}</td><td>${esc(p.passport)}</td><td>${esc(p.flight)}</td><td>${esc(p.room)}</td><td>${money(p.balance)}</td><td>${chip(statusHe(p.status),statusType(p.status))}</td><td><button class="row-action" onclick="openPersonForm(${p.id})">עריכה</button></td></tr>`).join('')}</tbody></table></div>`}
function filterPeople(){const s=q('#peopleSearch').value.toLowerCase();q('#peopleTable').innerHTML=peopleTable(state.people.filter(p=>Object.values(p).join(' ').toLowerCase().includes(s)))}
function openPersonForm(id){const p=state.people.find(x=>x.id===id)||{name:'',phone:'',passport:'',flight:'',room:'',paid:0,balance:0,status:'pending'};openModal(id?'עריכת משתתף':'משתתף חדש',`<form id="personForm" class="form-grid"><div class="field"><label>שם מלא</label><input name="name" required value="${esc(p.name)}"></div><div class="field"><label>טלפון</label><input name="phone" value="${esc(p.phone)}"></div><div class="field"><label>תוקף דרכון</label><input name="passport" placeholder="DD/MM/YYYY" value="${esc(p.passport)}"></div><div class="field"><label>טיסה</label><input name="flight" value="${esc(p.flight)}"></div><div class="field"><label>לינה</label><input name="room" value="${esc(p.room)}"></div><div class="field"><label>יתרה</label><input type="number" name="balance" value="${Number(p.balance||0)}"></div><div class="field"><label>סטטוס</label><select name="status"><option value="pending" ${p.status==='pending'?'selected':''}>ממתין</option><option value="confirmed" ${p.status==='confirmed'?'selected':''}>מאושר</option></select></div></form>`,()=>{const f=new FormData(q('#personForm'));const obj=Object.fromEntries(f);obj.balance=Number(obj.balance||0);if(id)Object.assign(p,obj);else state.people.push({...obj,id:Date.now(),paid:0});save();closeModal();renderPeople();toast('נשמר בהצלחה')})}

function renderStay(){const total=state.apartments.reduce((a,x)=>a+x.capacity,0),occ=state.apartments.reduce((a,x)=>a+x.occupied,0);q('#view').innerHTML=`<section class="page">${pageHead('לינה','דירות, חדרים, מקומות שינה ושיבוצים',`<button class="btn primary" onclick="openApartmentForm()">＋ דירה</button>`)}<div class="kpi-row"><div class="kpi"><small>סה״כ מקומות</small><strong>${total}</strong></div><div class="kpi"><small>משובצים</small><strong>${occ}</strong></div><div class="kpi"><small>פנויים</small><strong>${total-occ}</strong></div></div><div class="entity-grid">${state.apartments.map(a=>`<article class="entity-card"><h3>${esc(a.name)}</h3><p>📍 ${esc(a.address)}</p><p>מנהל: ${esc(a.manager)}</p><p><strong>${a.occupied}/${a.capacity}</strong> תפוסה</p><div class="progress"><span style="width:${Math.round(a.occupied/a.capacity*100)}%"></span></div><div class="actions"><button class="btn secondary" onclick="openApartmentForm(${a.id})">עריכה</button><button class="btn secondary" onclick="navigate('issues')">תקלות</button></div></article>`).join('')}</div><div class="card"><div class="section-head"><div class="section-title">שיבוצי משתתפים</div></div>${peopleTable(state.people)}</div></section>`}
function openApartmentForm(id){const a=state.apartments.find(x=>x.id===id)||{name:'',address:'',capacity:1,occupied:0,manager:'',status:'active'};openModal(id?'עריכת דירה':'דירה חדשה',`<form id="aptForm" class="form-grid"><div class="field"><label>שם</label><input name="name" required value="${esc(a.name)}"></div><div class="field"><label>כתובת</label><input name="address" value="${esc(a.address)}"></div><div class="field"><label>קיבולת</label><input type="number" min="1" name="capacity" value="${a.capacity}"></div><div class="field"><label>תפוסה</label><input type="number" min="0" name="occupied" value="${a.occupied}"></div><div class="field"><label>מנהל</label><input name="manager" value="${esc(a.manager)}"></div></form>`,()=>{const obj=Object.fromEntries(new FormData(q('#aptForm')));obj.capacity=Number(obj.capacity);obj.occupied=Number(obj.occupied);if(id)Object.assign(a,obj);else state.apartments.push({...obj,id:Date.now(),status:'active'});save();closeModal();renderStay();toast('נשמר')})}

function renderFlights(){q('#view').innerHTML=`<section class="page">${pageHead('טיסות','ניהול טיסות הלוך וחזור ושיוך נוסעים',`<button class="btn primary" onclick="openFlightForm()">＋ טיסה</button>`)}<div class="entity-grid">${state.flights.map(f=>`<article class="entity-card"><h3>✈ ${esc(f.number)}</h3><p><strong>${esc(f.from)} → ${esc(f.to)}</strong></p><p>יציאה: ${esc(f.depart)}</p><p>נחיתה: ${esc(f.arrive)}</p><p>${f.passengers} נוסעים · ${chip(statusHe(f.status),statusType(f.status))}</p><div class="actions"><button class="btn secondary" onclick="openFlightForm(${f.id})">עריכה</button></div></article>`).join('')}</div></section>`}
function openFlightForm(id){const f=state.flights.find(x=>x.id===id)||{number:'',from:'',to:'',depart:'',arrive:'',passengers:0,status:'planned'};openModal(id?'עריכת טיסה':'טיסה חדשה',`<form id="flightForm" class="form-grid"><div class="field"><label>מספר טיסה</label><input name="number" required value="${esc(f.number)}"></div><div class="field"><label>מוצא</label><input name="from" value="${esc(f.from)}"></div><div class="field"><label>יעד</label><input name="to" value="${esc(f.to)}"></div><div class="field"><label>יציאה</label><input name="depart" value="${esc(f.depart)}"></div><div class="field"><label>נחיתה</label><input name="arrive" value="${esc(f.arrive)}"></div><div class="field"><label>נוסעים</label><input type="number" name="passengers" value="${f.passengers}"></div><div class="field"><label>סטטוס</label><select name="status"><option value="planned" ${f.status==='planned'?'selected':''}>מתוכנן</option><option value="confirmed" ${f.status==='confirmed'?'selected':''}>מאושר</option></select></div></form>`,()=>{const obj=Object.fromEntries(new FormData(q('#flightForm')));obj.passengers=Number(obj.passengers);if(id)Object.assign(f,obj);else state.flights.push({...obj,id:Date.now()});save();closeModal();renderFlights();toast('נשמר')})}

function renderTransport(){q('#view').innerHTML=`<section class="page">${pageHead('תחבורה','נהגים, רכבים והקצאות',`<button class="btn primary" onclick="openTransportForm()">＋ רכב / נהג</button>`)}<div class="entity-grid">${state.transport.map(v=>`<article class="entity-card"><h3>🚐 ${esc(v.name)}</h3><p>${esc(v.type)} · ${v.capacity} מקומות</p><p>נהג: <strong>${esc(v.driver)}</strong></p><p>${esc(v.phone)}</p><p>${chip(statusHe(v.status),statusType(v.status))}</p><div class="actions"><button class="btn secondary" onclick="openTransportForm(${v.id})">עריכה</button></div></article>`).join('')}</div></section>`}
function openTransportForm(id){const v=state.transport.find(x=>x.id===id)||{type:'Van',name:'',driver:'',phone:'',capacity:8,status:'available'};openModal(id?'עריכת רכב/נהג':'רכב/נהג חדש',`<form id="trForm" class="form-grid"><div class="field"><label>שם רכב</label><input name="name" value="${esc(v.name)}"></div><div class="field"><label>סוג</label><input name="type" value="${esc(v.type)}"></div><div class="field"><label>נהג</label><input name="driver" value="${esc(v.driver)}"></div><div class="field"><label>טלפון</label><input name="phone" value="${esc(v.phone)}"></div><div class="field"><label>קיבולת</label><input type="number" name="capacity" value="${v.capacity}"></div><div class="field"><label>סטטוס</label><select name="status"><option value="available" ${v.status==='available'?'selected':''}>זמין</option><option value="busy" ${v.status==='busy'?'selected':''}>עסוק</option></select></div></form>`,()=>{const obj=Object.fromEntries(new FormData(q('#trForm')));obj.capacity=Number(obj.capacity);if(id)Object.assign(v,obj);else state.transport.push({...obj,id:Date.now()});save();closeModal();renderTransport();toast('נשמר')})}

function renderTasks(){q('#view').innerHTML=`<section class="page">${pageHead('משימות','מה צריך לקרות, מי אחראי ומתי',`<button class="btn primary" onclick="openTaskForm()">＋ משימה</button>`)}<div class="list">${state.tasks.map(x=>`<div class="row"><div class="row-icon">☑</div><div class="row-main"><strong>${esc(x.title)}</strong><span>${esc(x.owner)} · עד ${esc(x.due)} · ${esc(x.priority)}</span></div><button class="btn ${x.status==='done'?'secondary':'primary'}" onclick="toggleTask(${x.id})">${x.status==='done'?'בוצע':'סמן בוצע'}</button></div>`).join('')}</div></section>`}
function toggleTask(id){const x=state.tasks.find(x=>x.id===id);x.status=x.status==='done'?'pending':'done';save();renderTasks()}
function openTaskForm(){openModal('משימה חדשה',`<form id="taskForm" class="form-grid"><div class="field full"><label>משימה</label><input name="title" required></div><div class="field"><label>אחראי</label><input name="owner"></div><div class="field"><label>תאריך יעד</label><input type="date" name="due"></div><div class="field"><label>עדיפות</label><select name="priority"><option value="normal">רגילה</option><option value="high">גבוהה</option><option value="urgent">דחופה</option></select></div></form>`,()=>{const obj=Object.fromEntries(new FormData(q('#taskForm')));state.tasks.push({...obj,id:Date.now(),status:'pending'});save();closeModal();renderTasks();toast('משימה נוספה')})}

function renderFinance(){const due=state.payments.reduce((a,x)=>a+x.due,0),paid=state.payments.reduce((a,x)=>a+x.paid,0),expenses=state.expenses.reduce((a,x)=>a+x.amount,0);q('#view').innerHTML=`<section class="page">${pageHead('כספים','תשלומי משתתפים, יתרות והוצאות',`<button class="btn primary" onclick="openPaymentForm()">＋ תשלום</button>`)}<div class="kpi-row"><div class="kpi"><small>נדרש לגבייה</small><strong>${money(due)}</strong></div><div class="kpi"><small>נגבה</small><strong>${money(paid)}</strong></div><div class="kpi"><small>הוצאות</small><strong>${money(expenses)}</strong></div></div><div class="split"><div class="card"><div class="section-head"><div class="section-title">תשלומי משתתפים</div></div><div class="table-wrap"><table><thead><tr><th>משתתף</th><th>נדרש</th><th>שולם</th><th>יתרה</th><th>סטטוס</th></tr></thead><tbody>${state.payments.map(p=>`<tr><td>${esc(p.person)}</td><td>${money(p.due)}</td><td>${money(p.paid)}</td><td>${money(p.due-p.paid)}</td><td>${chip(statusHe(p.status),statusType(p.status))}</td></tr>`).join('')}</tbody></table></div></div><div class="card"><div class="section-head"><div class="section-title">הוצאות</div><button class="section-link" onclick="openExpenseForm()">＋ הוצאה</button></div><div class="list">${state.expenses.map(e=>`<div class="row"><div class="row-icon gold">▣</div><div class="row-main"><strong>${esc(e.description)}</strong><span>${esc(e.category)} · ${esc(e.date)}</span></div><strong>${money(e.amount)}</strong></div>`).join('')}</div></div></div></section>`}
function openPaymentForm(){openModal('רישום תשלום',`<form id="payForm" class="form-grid"><div class="field full"><label>משתתף</label><input name="person" required></div><div class="field"><label>סכום נדרש</label><input type="number" name="due" value="1850"></div><div class="field"><label>שולם</label><input type="number" name="paid" value="0"></div></form>`,()=>{const o=Object.fromEntries(new FormData(q('#payForm')));o.due=Number(o.due);o.paid=Number(o.paid);o.status=o.paid>=o.due?'paid':o.paid>0?'partial':'pending';state.payments.push({...o,id:Date.now()});save();closeModal();renderFinance();toast('התשלום נשמר')})}
function openExpenseForm(){openModal('הוצאה חדשה',`<form id="expForm" class="form-grid"><div class="field"><label>קטגוריה</label><input name="category"></div><div class="field"><label>סכום</label><input type="number" name="amount"></div><div class="field full"><label>תיאור</label><input name="description"></div><div class="field"><label>תאריך</label><input type="date" name="date"></div></form>`,()=>{const o=Object.fromEntries(new FormData(q('#expForm')));o.amount=Number(o.amount);state.expenses.push({...o,id:Date.now()});save();closeModal();renderFinance();toast('ההוצאה נשמרה')})}

function renderIssues(){q('#view').innerHTML=`<section class="page">${pageHead('תקלות בדירות','רישום, אחריות ומעקב עד פתרון',`<button class="btn primary" onclick="openIssueForm()">＋ תקלה</button>`)}<div class="list">${state.issues.map(i=>`<div class="row"><div class="row-icon ${i.severity==='high'?'red':'gold'}">⚠</div><div class="row-main"><strong>${esc(i.title)}</strong><span>${esc(i.apartment)} · אחראי ${esc(i.owner)} · ${esc(i.severity)}</span></div><button class="btn ${i.status==='resolved'?'secondary':'primary'}" onclick="toggleIssue(${i.id})">${i.status==='resolved'?'נפתר':'סמן טופל'}</button></div>`).join('')}</div></section>`}
function toggleIssue(id){const i=state.issues.find(x=>x.id===id);i.status=i.status==='resolved'?'open':'resolved';save();renderIssues()}
function openIssueForm(){openModal('תקלה חדשה',`<form id="issueForm" class="form-grid"><div class="field"><label>דירה</label><input name="apartment"></div><div class="field"><label>אחראי</label><input name="owner"></div><div class="field full"><label>תיאור</label><input name="title" required></div><div class="field"><label>חומרה</label><select name="severity"><option value="low">נמוכה</option><option value="medium">בינונית</option><option value="high">גבוהה</option></select></div></form>`,()=>{const o=Object.fromEntries(new FormData(q('#issueForm')));state.issues.push({...o,id:Date.now(),status:'open'});save();closeModal();renderIssues();toast('התקלה נרשמה')})}

function renderSchedule(){q('#view').innerHTML=`<section class="page">${pageHead('לוח זמנים','אירועים תפעוליים, טיסות, נסיעות ומשימות',`<button class="btn primary" onclick="openScheduleForm()">＋ אירוע</button>`)}<div class="list">${[...state.schedule].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(i=>`<div class="row"><div class="date-badge"><small>${esc(i.date.slice(5,7))}</small><strong>${esc(i.date.slice(8,10))}</strong></div><div class="row-main"><strong>${esc(i.title)}</strong><span>${esc(i.date)} · ${esc(i.time)}</span></div>${chip(i.type)}</div>`).join('')}</div></section>`}
function openScheduleForm(){openModal('אירוע חדש',`<form id="schedForm" class="form-grid"><div class="field full"><label>כותרת</label><input name="title" required></div><div class="field"><label>תאריך</label><input type="date" name="date"></div><div class="field"><label>שעה</label><input type="time" name="time"></div><div class="field"><label>סוג</label><input name="type" value="meeting"></div></form>`,()=>{const o=Object.fromEntries(new FormData(q('#schedForm')));state.schedule.push({...o,id:Date.now()});save();closeModal();renderSchedule();toast('האירוע נוסף')})}

function renderMore(){const items=[['flights','✈','טיסות','טיסות, נוסעים וזמנים'],['transport','🚐','תחבורה','נהגים ורכבים'],['tasks','☑','משימות','אחריות ומעקב'],['issues','⚠','תקלות','תקלות בדירות'],['schedule','🗓','לוח זמנים','אירועים ותפעול'],['settings','⚙','הגדרות','אירוע, שפה ונתונים']];q('#view').innerHTML=`<section class="page">${pageHead('עוד','כל כלי הניהול הנוספים')}<div class="more-grid">${items.map(x=>`<button class="menu-card" onclick="navigate('${x[0]}')"><span class="menu-icon">${x[1]}</span><span><strong>${x[2]}</strong><span>${x[3]}</span></span></button>`).join('')}</div><div class="card"><div class="section-title">📦 גיבוי ונתונים</div><p style="color:var(--muted)">הנתונים נשמרים בדפדפן במכשיר זה. ניתן לייצא או לייבא גיבוי JSON.</p><div class="toolbar"><button class="btn secondary" onclick="exportBackup()">ייצוא גיבוי</button><label class="btn secondary" style="cursor:pointer">ייבוא גיבוי<input type="file" accept="application/json" onchange="importBackup(event)" hidden></label><button class="btn danger" onclick="resetDemo()">איפוס לנתוני דוגמה</button></div></div></section>`}
function renderSettings(){const s=state.settings;q('#view').innerHTML=`<section class="page">${pageHead('הגדרות','פרטי האירוע והעדפות מערכת')}<div class="settings-panel"><div class="setting-card"><h3>פרטי האירוע</h3><form id="settingsForm" class="form-grid"><div class="field full"><label>שם האירוע</label><input name="eventName" value="${esc(s.eventName)}"></div><div class="field"><label>תאריך התחלה</label><input type="date" name="start" value="${esc(s.start)}"></div><div class="field"><label>תאריך סיום</label><input type="date" name="end" value="${esc(s.end)}"></div><div class="field full"><label>מיקום</label><input name="location" value="${esc(s.location)}"></div><div class="field"><label>מטבע</label><select name="currency"><option ${s.currency==='USD'?'selected':''}>USD</option><option ${s.currency==='ILS'?'selected':''}>ILS</option><option ${s.currency==='EUR'?'selected':''}>EUR</option></select></div><div class="field"><label>שפה</label><select name="lang"><option value="he" ${s.lang==='he'?'selected':''}>עברית</option><option value="en" ${s.lang==='en'?'selected':''}>English</option></select></div></form><div class="modal-actions"><button class="btn primary" onclick="saveSettings()">שמור</button></div></div><div class="setting-card"><h3>מצב המערכת</h3><p>משתתפים: <strong>${state.people.length}</strong></p><p>דירות: <strong>${state.apartments.length}</strong></p><p>טיסות: <strong>${state.flights.length}</strong></p><p>משימות פתוחות: <strong>${state.tasks.filter(x=>x.status!=='done').length}</strong></p><p>גרסת Web: <strong>1.0</strong></p></div></div></section>`}
function saveSettings(){const o=Object.fromEntries(new FormData(q('#settingsForm')));Object.assign(state.settings,o);save();applyLang();renderSettings();toast('ההגדרות נשמרו')}

function openModal(title,body,onSave){q('#modalRoot').innerHTML=`<div class="modal-backdrop" onclick="if(event.target===this)closeModal()"><div class="modal"><div class="modal-head"><h2>${title}</h2><button class="modal-close" onclick="closeModal()">×</button></div>${body}<div class="modal-actions"><button class="btn secondary" onclick="closeModal()">ביטול</button><button id="modalSave" class="btn primary">שמור</button></div></div></div>`;q('#modalSave').onclick=onSave}
function closeModal(){q('#modalRoot').innerHTML=''}
function quickAdd(){const menu=[['משתתף',()=>openPersonForm()],['טיסה',()=>openFlightForm()],['משימה',()=>openTaskForm()],['תקלה',()=>openIssueForm()],['אירוע',()=>openScheduleForm()]];openModal('הוספה מהירה',`<div class="more-grid">${menu.map((x,i)=>`<button class="menu-card" onclick="quickAddAction(${i})"><span class="menu-icon">＋</span><span><strong>${x[0]}</strong></span></button>`).join('')}</div>`,()=>closeModal());window._quickMenu=menu}
function quickAddAction(i){closeModal();window._quickMenu[i][1]()}
function exportBackup(){download('uman-event-manager-backup.json',JSON.stringify(state,null,2),'application/json')}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);save();navigate('dashboard');toast('הגיבוי יובא בהצלחה')}catch{toast('קובץ גיבוי לא תקין')}};r.readAsText(f)}
function exportCsv(type){const rows=state[type]||[];if(!rows.length)return;const keys=Object.keys(rows[0]);const csv=[keys.join(','),...rows.map(r=>keys.map(k=>`"${String(r[k]??'').replaceAll('"','""')}"`).join(','))].join('\n');download(`${type}.csv`,'\ufeff'+csv,'text/csv;charset=utf-8')}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function resetDemo(){if(confirm('לאפס את כל הנתונים לנתוני הדוגמה?')){state=structuredClone(seed);save();applyLang();navigate('dashboard');toast('הנתונים אופסו')}}
function applyLang(){document.documentElement.lang=state.settings.lang;document.documentElement.dir=state.settings.lang==='he'?'rtl':'ltr';qa('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));qa('#langToggle span').forEach(el=>el.classList.toggle('active',el.dataset.lang===state.settings.lang))}
q('#langToggle').onclick=()=>{state.settings.lang=state.settings.lang==='he'?'en':'he';save();applyLang();navigate(route)};
q('#quickAdd').onclick=quickAdd;
qa('.nav-item').forEach(b=>b.onclick=()=>navigate(b.dataset.route));
window.navigate=navigate;Object.assign(window,{openPersonForm,filterPeople,openApartmentForm,openFlightForm,openTransportForm,openTaskForm,toggleTask,openPaymentForm,openExpenseForm,openIssueForm,toggleIssue,openScheduleForm,saveSettings,closeModal,quickAddAction,exportBackup,importBackup,exportCsv,resetDemo});
applyLang();navigate((location.hash||'#dashboard').slice(1));
setInterval(()=>{if(route==='dashboard')renderDashboard()},1000);
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
