import type { EventRow } from "./model";
// Mirrors the existing events_base_currency_iso constraint; tested against its migration.
export const eventCurrencies = [
  "AED",
  "AFN",
  "ALL",
  "AMD",
  "AOA",
  "ARS",
  "AUD",
  "AWG",
  "AZN",
  "BAM",
  "BBD",
  "BDT",
  "BHD",
  "BIF",
  "BMD",
  "BND",
  "BOB",
  "BOV",
  "BRL",
  "BSD",
  "BTN",
  "BWP",
  "BYN",
  "BZD",
  "CAD",
  "CDF",
  "CHE",
  "CHF",
  "CHW",
  "CLF",
  "CLP",
  "CNY",
  "COP",
  "COU",
  "CRC",
  "CUP",
  "CVE",
  "CZK",
  "DJF",
  "DKK",
  "DOP",
  "DZD",
  "EGP",
  "ERN",
  "ETB",
  "EUR",
  "FJD",
  "FKP",
  "GBP",
  "GEL",
  "GHS",
  "GIP",
  "GMD",
  "GNF",
  "GTQ",
  "GYD",
  "HKD",
  "HNL",
  "HTG",
  "HUF",
  "IDR",
  "ILS",
  "INR",
  "IQD",
  "IRR",
  "ISK",
  "JMD",
  "JOD",
  "JPY",
  "KES",
  "KGS",
  "KHR",
  "KMF",
  "KPW",
  "KRW",
  "KWD",
  "KYD",
  "KZT",
  "LAK",
  "LBP",
  "LKR",
  "LRD",
  "LSL",
  "LYD",
  "MAD",
  "MDL",
  "MGA",
  "MKD",
  "MMK",
  "MNT",
  "MOP",
  "MRU",
  "MUR",
  "MVR",
  "MWK",
  "MXN",
  "MXV",
  "MYR",
  "MZN",
  "NAD",
  "NGN",
  "NIO",
  "NOK",
  "NPR",
  "NZD",
  "OMR",
  "PAB",
  "PEN",
  "PGK",
  "PHP",
  "PKR",
  "PLN",
  "PYG",
  "QAR",
  "RON",
  "RSD",
  "RUB",
  "RWF",
  "SAR",
  "SBD",
  "SCR",
  "SDG",
  "SEK",
  "SGD",
  "SHP",
  "SLE",
  "SOS",
  "SRD",
  "SSP",
  "STN",
  "SVC",
  "SYP",
  "SZL",
  "THB",
  "TJS",
  "TMT",
  "TND",
  "TOP",
  "TRY",
  "TTD",
  "TWD",
  "TZS",
  "UAH",
  "UGX",
  "USD",
  "USN",
  "UYI",
  "UYU",
  "UYW",
  "UZS",
  "VED",
  "VES",
  "VND",
  "VUV",
  "WST",
  "XAD",
  "XAF",
  "XAG",
  "XAU",
  "XBA",
  "XBB",
  "XBC",
  "XBD",
  "XCD",
  "XCG",
  "XDR",
  "XOF",
  "XPD",
  "XPF",
  "XPT",
  "XSU",
  "XUA",
  "YER",
  "ZAR",
  "ZMW",
  "ZWG",
];
export const eventFields = [
  ["name", "eventName", "text"],
  ["hebrew_name", "hebrewName", "text"],
  ["start_date", "startDate", "date"],
  ["end_date", "endDate", "date"],
  ["year", "year", "number"],
  ["base_currency", "baseCurrency", "text"],
  ["description", "description", "text"],
  ["manager_notes", "managerNotes", "text"],
] as const;
export type EventDraft = Record<string, string>;
export const eventValues = (event?: EventRow): EventDraft =>
  Object.fromEntries(
    eventFields.map(([k]) => [
      k,
      event ? String(event[k] ?? "") : k === "base_currency" ? "USD" : "",
    ]),
  );
const calendarDate = (v: string) =>
  /^\d{4}-\d{2}-\d{2}$/.test(v) &&
  !Number.isNaN(Date.parse(v)) &&
  new Date(v).toISOString().slice(0, 10) === v;
export function validateEvent(d: EventDraft): Record<string, string> {
  const errors: Record<string, string> = {};
  if (!d.name.trim() || d.name.trim().length > 200)
    errors.name = "eventNameInvalid";
  for (const [k, max] of [
    ["hebrew_name", 200],
    ["description", 10000],
    ["manager_notes", 10000],
  ] as const)
    if (d[k].length > max) errors[k] = "eventTextTooLong";
  if (
    d.year &&
    (!/^\d{4}$/.test(d.year) || Number(d.year) < 1900 || Number(d.year) > 2200)
  )
    errors.year = "eventYearInvalid";
  for (const k of ["start_date", "end_date"])
    if (d[k] && !calendarDate(d[k])) errors[k] = "eventDateInvalid";
  if (d.start_date && d.end_date && d.end_date <= d.start_date)
    errors.end_date = "eventRangeInvalid";
  if (d.base_currency && !eventCurrencies.includes(d.base_currency))
    errors.base_currency = "eventCurrencyInvalid";
  return errors;
}
export function eventPayload(d: EventDraft) {
  if (Object.keys(validateEvent(d)).length) throw { code: "22023" };
  return Object.fromEntries(
    eventFields.map(([k]) => [
      k,
      d[k] === "" ? null : k === "year" ? Number(d[k]) : d[k],
    ]),
  );
}
